
spring:
  application:
    name: cloud-config-client
  profiles:
    active: dev

eureka:
  client:
    register-with-eureka: true  
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

---
info: dev-modify version 1
spring: 
  profiles: dev

---
info: prod
spring:
  profiles: prod
